<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KdramaSeeder extends Seeder
{
    /**
     * Seed data untuk tabel `kdramas`.
     *
     * Jalankan dengan:
     *   php spark db:seed KdramaSeeder
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Move to Heaven',
                'aired_date' => 'May 14, 2021',
                'year_of_release' => 2021,
                'original_network' => 'Netflix',
                'aired_on' => 'Friday',
                'number_of_episodes' => 10,
                'duration' => '52 min.',
                'content_rating' => '18+ Restricted (violence & profanity)',
                'rating' => 9.2,
                'synopsis' => 'Geu Roo is a young autistic man. He works for his father’s business “Move To Heaven.” Their job is to arrange items left by deceased people.',
                'genre' => 'Life, Drama, Family',
                'tags' => 'Autism, Uncle-Nephew Relationship, Death, Savant Syndrome, Mourning, Tearjerker, Father-Son Relationship, Life Lesson',
                'director' => 'Kim Sung Ho',
                'screenwriter' => 'Yoon Ji Ryun',
                'cast_members' => 'Lee Je Hoon, Tang Jun Sang, Hong Seung Hee, Jung Suk Yong, Jung Young Joo, Lee Moon Shik',
                'production_companies' => 'Page One Film, Number Three Pictures',
                'rank' => 1,
            ],

            [
                'name' => 'Flower of Evil',
                'aired_date' => 'Jul 29, 2020 - Sep 23, 2020',
                'year_of_release' => 2020,
                'original_network' => 'tvN',
                'aired_on' => 'Wednesday, Thursday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 10 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'Although Baek Hee Sung is hiding a dark secret surrounding his true identity, he has established a happy family life and a successful career.',
                'genre' => 'Thriller, Romance, Crime, Melodrama',
                'tags' => 'Married Couple, Deception, Suspense, Family Secret, Hidden Personality, Investigation, Serial Killer, Psychopath',
                'director' => 'Kim Chul Gyu, Yoon Jong Ho',
                'screenwriter' => 'Yoo Jung Hee',
                'cast_members' => 'Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo Hyun Woo, Nam Ki Ae, Son Jong Hak',
                'production_companies' => 'Monster Union',
                'rank' => 2,
            ],

            [
                'name' => 'Hospital Playlist',
                'aired_date' => 'Mar 12, 2020 - May 28, 2020',
                'year_of_release' => 2020,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Thursday',
                'number_of_episodes' => 12,
                'duration' => '1 hr. 30 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'The stories of people going through their days that are seemingly ordinary but actually special, at the hospital.',
                'genre' => 'Friendship, Romance, Life, Medical',
                'tags' => 'Strong Friendship, Multiple Mains, Best Friends, Hospital, Slow Romance, Strong Female Lead, Multiple Couples, Comedy',
                'director' => 'Shin Won Ho',
                'screenwriter' => 'Lee Woo Jung',
                'cast_members' => 'Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim Dae Myung, Jeon Mi Do, Shin Hyun Bin',
                'production_companies' => 'Egg Is Coming, CJ ENM',
                'rank' => 3,
            ],

            [
                'name' => 'Hospital Playlist 2',
                'aired_date' => 'Jun 17, 2021 - Sep 16, 2021',
                'year_of_release' => 2021,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Thursday',
                'number_of_episodes' => 12,
                'duration' => '1 hr. 40 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'Everyday is extraordinary for five doctors and their patients inside a hospital.',
                'genre' => 'Friendship, Romance, Life, Medical',
                'tags' => 'Workplace, Strong Friendship, Best Friends, Multiple Mains, Band, Music, Strong Female Lead, Multiple Couples, Comedy, Hospital',
                'director' => 'Shin Won Ho',
                'screenwriter' => 'Lee Woo Jung',
                'cast_members' => 'Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim Dae Myung, Jeon Mi Do, Shin Hyun Bin',
                'production_companies' => 'Egg Is Coming, CJ ENM',
                'rank' => 4,
            ],

            [
                'name' => 'My Mister',
                'aired_date' => 'Mar 21, 2018 - May 17, 2018',
                'year_of_release' => 2018,
                'original_network' => 'tvN',
                'aired_on' => 'Wednesday, Thursday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 17 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'Park Dong Hoon is a middle-aged engineer who is married to attorney Kang Yoon Hee.',
                'genre' => 'Psychological, Life, Drama, Family',
                'tags' => 'Age Gap, Nice Male Lead, Strong Female Lead, Hardship, Smart Female Lead, Healing, Depression, Workplace, Infidelity',
                'director' => 'Kim Won Suk, Kim Sang Woo',
                'screenwriter' => 'Park Hae Young',
                'cast_members' => 'Lee Sun Kyun, IU, Park Ho San, Song Sae Byuk, Lee Ji Ah, Kim Young Min',
                'production_companies' => 'Chorokbaem Media',
                'rank' => 5,
            ],

            [
                'name' => 'Reply 1988',
                'aired_date' => 'Nov 6, 2015 - Jan 16, 2016',
                'year_of_release' => 2015,
                'original_network' => 'tvN',
                'aired_on' => 'Friday, Saturday',
                'number_of_episodes' => 20,
                'duration' => '1 hr. 40 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'Five childhood friends who all live in the same neighborhood of Seoul lean on each other to survive their challenging teen years.',
                'genre' => 'Comedy, Romance, Youth, Family',
                'tags' => 'Neighbors, Slice Of Life, Childhood Friends, Multiple Couples, Nostalgia, Poor Family, Love Triangle, High School',
                'director' => 'Shin Won Ho, Yoo Hak Chan',
                'screenwriter' => 'Lee Woo Jung',
                'cast_members' => 'Lee Hye Ri, Go Kyung Pyo, Ryu Joon Yeol, Park Bo Gum, Lee Dong Hwi, Sung Dong Il',
                'production_companies' => 'CJ ENM',
                'rank' => 6,
            ],

            [
                'name' => 'Weak Hero Class 1',
                'aired_date' => 'Nov 18, 2022',
                'year_of_release' => 2022,
                'original_network' => 'Wavve',
                'aired_on' => 'Friday',
                'number_of_episodes' => 8,
                'duration' => '40 min.',
                'content_rating' => '18+ Restricted (violence & profanity)',
                'rating' => 9.1,
                'synopsis' => 'Yeon Shi Eun is a model student who ranks at the top of his high school. Physically weak, he uses his intelligence and psychology to fight violence.',
                'genre' => 'Action, Youth, Drama',
                'tags' => 'Bromance, Smart Male Lead, Violence, School Bullying, Webtoon, Skilled Fighter, Hidden Past',
                'director' => 'You Su Min',
                'screenwriter' => 'Jun Hee Han',
                'cast_members' => 'Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim Su Gyeom, Lee Yeon, Shin Seung Ho',
                'production_companies' => 'PlayList Global',
                'rank' => 7,
            ],

            [
                'name' => 'Prison Playbook',
                'aired_date' => 'Nov 22, 2017 - Jan 18, 2018',
                'year_of_release' => 2017,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Wednesday, Thursday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 32 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.1,
                'synopsis' => 'Kim Je Hyuk, a famous baseball player, is arrested after using excessive force while chasing a man trying to sexually assault his sister.',
                'genre' => 'Comedy, Crime, Life, Drama',
                'tags' => 'Prison, Bromance, Wrongfully Accused, Life Lesson, Strong Male Lead, Baseball, Gangster, Murder',
                'director' => 'Shin Won Ho',
                'screenwriter' => 'Jung Bo Hoon, Lee Woo Jung',
                'cast_members' => 'Park Hae Soo, Jung Kyung Ho, Krystal Jung, Im Hwa Young, Ye Soo Jung, Kim Kyung Nam',
                'production_companies' => 'tvN',
                'rank' => 8,
            ],

            [
                'name' => 'Alchemy of Souls',
                'aired_date' => 'Jun 18, 2022 - Aug 28, 2022',
                'year_of_release' => 2022,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Saturday, Sunday',
                'number_of_episodes' => 20,
                'duration' => '1 hr. 20 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'Set in a fictional country called Daeho, young mages overcome their twisted fates through forbidden magic that allows souls to switch bodies.',
                'genre' => 'Action, Historical, Romance, Fantasy',
                'tags' => 'Magical Power, Supernatural, Transmigration, Strong Female Lead, Hidden Identity, Body Swap',
                'director' => 'Park Joon Hwa',
                'screenwriter' => 'Hong Jung Eun, Hong Mi Ran',
                'cast_members' => 'Lee Jae Wook, Jung So Min, Hwang Min Hyun, Shin Seung Ho, Yoo Joon Sang, Oh Na Ra',
                'production_companies' => 'Studio Dragon, High Quality',
                'rank' => 9,
            ],

            [
                'name' => 'Extraordinary Attorney Woo',
                'aired_date' => 'Jun 29, 2022 - Aug 18, 2022',
                'year_of_release' => 2022,
                'original_network' => 'ENA, Netflix',
                'aired_on' => 'Wednesday, Thursday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 17 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'Woo Young Woo is a brilliant lawyer who graduated at the top of her class and works at a major law firm while navigating social interactions.',
                'genre' => 'Law, Romance, Life, Drama',
                'tags' => 'Attorney Female Lead, Smart Female Lead, Law Firm, Workplace, Courtroom Setting, Father-Daughter Relationship',
                'director' => 'Yoo In Shik',
                'screenwriter' => 'Moon Ji Won',
                'cast_members' => 'Park Eun Bin, Kang Tae Oh, Kang Ki Young, Jeon Bae Soo, Baek Ji Won, Jin Kyung',
                'production_companies' => 'AStory, KT Studio Genie, Nangman Crew',
                'rank' => 10,
            ],

            [
                'name' => 'Mr. Queen',
                'aired_date' => 'Dec 12, 2020 - Feb 14, 2021',
                'year_of_release' => 2020,
                'original_network' => 'tvN',
                'aired_on' => 'Saturday, Sunday',
                'number_of_episodes' => 20,
                'duration' => '1 hr. 20 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'Jang Bong Hwan is a South Korean chef who finds himself in the body of the young queen Kim So Yong after a serious accident.',
                'genre' => 'Historical, Mystery, Comedy, Romance',
                'tags' => 'Smart Male Lead, Transmigration, Joseon Dynasty, Time Travel, Body Swap, Gender Swap, Power Struggle',
                'director' => 'Yoon Sung Shik',
                'screenwriter' => 'Park Kye Ok, Choi Ah Il',
                'cast_members' => 'Shin Hye Sun, Kim Jung Hyun, Bae Jong Ok, Kim Tae Woo, Jo Yun Hee, Seol In Ah',
                'production_companies' => 'Crave Works, YG Entertainment',
                'rank' => 11,
            ],

            [
                'name' => 'Mother',
                'aired_date' => 'Jan 24, 2018 - Mar 15, 2018',
                'year_of_release' => 2018,
                'original_network' => 'tvN',
                'aired_on' => 'Wednesday, Thursday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 3 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'A school teacher discovers that one of her students is being abused and decides to protect the girl by becoming her substitute mother.',
                'genre' => 'Thriller, Mystery, Psychological, Melodrama',
                'tags' => 'Mother-Daughter Relationship, Independent Female Lead, Orphan Female Lead, Adoption, Motherhood',
                'director' => 'Kim Chul Gyu, Yoon Hyun Gi',
                'screenwriter' => 'Jung Seo Kyung',
                'cast_members' => 'Lee Bo Young, Heo Yool, Lee Hye Young, Go Sung Hee, Lee Jae Yoon, Go Bo Gyeol',
                'production_companies' => 'The Unicorn',
                'rank' => 12,
            ],

            [
                'name' => 'It’s Okay to Not Be Okay',
                'aired_date' => 'Jun 20, 2020 - Aug 9, 2020',
                'year_of_release' => 2020,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Saturday, Sunday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 15 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'Moon Gang Tae is a community health worker at a psychiatric ward who meets Ko Moon Young, a successful writer with a difficult personality.',
                'genre' => 'Psychological, Comedy, Romance, Drama',
                'tags' => 'Sibling Relationship, Mental Health, Independent Female Lead, Healing, Caregiver, Childhood Connection, Psychiatry',
                'director' => 'Park Shin Woo, Jung Dong Yoon',
                'screenwriter' => 'Jo Yong',
                'cast_members' => 'Kim Soo Hyun, Seo Yea Ji, Oh Jung Se, Park Gyu Young, Jang Young Nam, Kim Chang Wan',
                'production_companies' => 'Story TV, Gold Medalist',
                'rank' => 13,
            ],

            [
                'name' => 'Crash Landing on You',
                'aired_date' => 'Dec 14, 2019 - Feb 16, 2020',
                'year_of_release' => 2019,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Sunday, Saturday',
                'number_of_episodes' => 16,
                'duration' => '1 hr. 25 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'After a paragliding accident, South Korean heiress Yoon Se Ri crash lands in North Korea and meets army officer Ri Jung Hyuk.',
                'genre' => 'Military, Comedy, Romance, Political',
                'tags' => 'North And South Korea, Star Crossed Lovers, Strong Male Lead, Army Officer, Rich Female Lead, Soldier',
                'director' => 'Lee Jeong Hyo',
                'screenwriter' => 'Park Ji Eun',
                'cast_members' => 'Hyun Bin, Son Ye Jin, Seo Ji Hye, Kim Jung Hyun, Yang Kyung Won, Lee Shin Young',
                'production_companies' => 'Studio Dragon, Culture Depot',
                'rank' => 14,
            ],

            [
                'name' => 'Vincenzo',
                'aired_date' => 'Feb 20, 2021 - May 2, 2021',
                'year_of_release' => 2021,
                'original_network' => 'Netflix, tvN',
                'aired_on' => 'Saturday, Sunday',
                'number_of_episodes' => 20,
                'duration' => '1 hr. 25 min.',
                'content_rating' => '15+ - Teens 15 or older',
                'rating' => 9.0,
                'synopsis' => 'An Italian-born Korean mafia consigliere returns to South Korea and becomes involved with a determined lawyer while taking on a powerful conglomerate.',
                'genre' => 'Comedy, Law, Crime, Drama',
                'tags' => 'Mafia, Revenge, Smart Male Lead, Eccentric Female Lead, Injustice, Bromance, Father-Daughter Relationship',
                'director' => 'Kim Hee Won',
                'screenwriter' => 'Park Jae Bum',
                'cast_members' => 'Song Joong Ki, Jeon Yeo Been, Ok Taec Yeon, Kim Yeo Jin, Jo Han Chul, Kwak Dong Yeon',
                'production_companies' => 'Logos Film',
                'rank' => 15,
            ],
        ];

        $now = date('Y-m-d H:i:s');

        foreach ($data as &$row) {
            $row['created_at'] = $now;
            $row['updated_at'] = $now;
        }
        unset($row);

        // Nama tabel harus sama dengan yang dibuat di migration: `kdramas`
        $builder = $this->db->table('kdramas');

        // Bersihkan dulu agar seeder bisa dijalankan berulang tanpa duplikasi
        $builder->truncate();

        $builder->insertBatch($data);
    }
}